extends Node

enum State { IDLE = 0, WALK, SIT, UNKNOWN = -1 }

# Gameplay actions
const ACTION_GP_MOVE_RIGHT		= "gp_move_right"
const ACTION_GP_MOVE_LEFT		= "gp_move_left"
const ACTION_GP_MOVE_UP			= "gp_move_up"
const ACTION_GP_MOVE_DOWN		= "gp_move_down"
const ACTION_GP_SIT				= "gp_sit"

# UI sctions
const ACTION_UI_QUIT_GAME		= "ui_quit_game"
const ACTION_UI_INVENTORY		= "ui_inventory"
const ACTION_UI_MINIMAP			= "ui_minimap"
const ACTION_UI_CHAT			= "ui_chat"

# Interactive/Emote actions
const ACTION_IM_1			= "smile_1"
const ACTION_IM_2			= "smile_2"
const ACTION_IM_3			= "smile_3"
const ACTION_IM_4			= "smile_4"
const ACTION_IM_5			= "smile_5"
const ACTION_IM_6			= "smile_6"
const ACTION_IM_7			= "smile_7"
const ACTION_IM_8			= "smile_8"
const ACTION_IM_9			= "smile_9"
const ACTION_IM_10			= "smile_10"
const ACTION_IM_11			= "smile_11"
const ACTION_IM_12			= "smile_12"
const ACTION_IM_13			= "smile_13"
const ACTION_IM_14			= "smile_14"
const ACTION_IM_15			= "smile_15"
const ACTION_IM_16			= "smile_16"
const ACTION_IM_17			= "smile_17"
const ACTION_IM_18			= "smile_18"
const ACTION_IM_19			= "smile_19"
const ACTION_IM_20			= "smile_20"
const ACTION_IM_21			= "smile_21"
const ACTION_IM_22			= "smile_22"
const ACTION_IM_23			= "smile_23"
const ACTION_IM_24			= "smile_24"
const ACTION_IM_25			= "smile_25"
const ACTION_IM_26			= "smile_26"
const ACTION_IM_27			= "smile_27"
const ACTION_IM_28			= "smile_28"
const ACTION_IM_29			= "smile_29"
const ACTION_IM_30			= "smile_30"
const ACTION_IM_31			= "smile_31"
const ACTION_IM_32			= "smile_32"
const ACTION_IM_33			= "smile_33"
const ACTION_IM_34			= "smile_34"
const ACTION_IM_35			= "smile_35"
const ACTION_IM_36			= "smile_36"
const ACTION_IM_37			= "smile_37"
const ACTION_IM_38			= "smile_38"
const ACTION_IM_39			= "smile_39"
