name: "godot-ci export"
on:
  push:
    branches:
      - '**'

jobs:
  builds:
    uses: ./.github/workflows/export.yml
    with:
      mode: debug
      features: sentry
    secrets: inherit

  snap:
    needs: builds
    uses: ./.github/workflows/snap.yml
    with:
      channel: edge
      publish: ${{ github.ref == 'refs/heads/master' && !github.event.repository.fork }}
    secrets: inherit
